server:
  port: 9002

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/category_db # --- IMPORTANT: Make sure a database named 'category_db' exists
    username: category_user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

resilience4j:
  circuitbreaker:
    instances:
      userCB:
        register-health-indicator: true
        sliding-window-size: 5
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0 # Traces 100% of requests. Good for development, might be lowered in production.
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # Default Zipkin server URL
